name: Run lint

on: [ push, pull_request, workflow_dispatch ]

jobs:
  lint:
    strategy:
      matrix:
        platform: [ "ubuntu-latest" ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Lint
      run: make lint
